### ISSUE TITLE
Invalid type marker byte

### ISSUE THREAD

**Issue by Maxxan** [FasterXML/jackson-dataformat-smile#27]
Some users get this error (using version 2.5.4). I don't know if the stream is corrupt somehow or if there is an actual bug when writing the stream (it writes the data to a file that is later read using Smile format). It's not over network, it's an application that saves the data to an internal smile file and reads from the file system it when loading the app (android).

com.fasterxml.jackson.core.JsonParseException: Invalid type marker byte 0x0 for expected value token
 at [Source: java.io.BufferedInputStream@3dae2fe1; line: -1, column: 1]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
	at com.fasterxml.jackson.dataformat.smile.SmileParser.nextToken(SmileParser.java:688)

**Comment by cowtowncoder** [comment]
I am not aware of existing bugs that would cause this. Since parser is seeing a null byte, it could well be that encoder had some issues with offsets, but that is just speculation.
So a reproducible test case is most likely needed to fix whatever the underlying problem is.

**Comment by cowtowncoder** [comment]
I still hope to get a reproduction of this, so leaving open for now.

**Comment by cowtowncoder** [comment]
Can not reproduce.
