### ISSUE TITLE
Deserialize error "Invalid type marker byte"

### ISSUE THREAD

**Issue by georgewfraser** [FasterXML/jackson-dataformat-smile#34]
Smile which is correctly decoded by smile-tool throws JsonParseException when deserialized with smile 2.7.1. The input smile corresponds to the JSON:

> [{ "(VLAN) Days of the week is member available for this work?": null }
]

It seems to depend very precisely on the field name.

Reproduce by cloning https://github.com/fivetran/smile-error and running `mvn test`.

Possibly related to #31  and #27

**Comment by georgewfraser** [comment]
Occurs with:

* jackson-core 2.60
* jackson-databind 2.6.0
* jackson-dataformat-smile 2.6.0

Does not occur with:

* jackson-core 2.60
* jackson-databind 2.6.0
* jackson-dataformat-smile 2.5.5

**Comment by georgewfraser** [comment]
I managed to create a test case that reproduces this error within jackson-dataformat-smile:

https://github.com/fivetran/jackson-dataformat-smile/tree/issue-34

**Comment by georgewfraser** [comment]
My understanding of the Jackson codebase is minimal but I think I this may be a fix:

https://github.com/fivetran/jackson-dataformat-smile/commit/b6670d964c4609a38f8c1fec06cb343f74030a73

I think I signed a CLA for a Jackson project at some point.

**Comment by cowtowncoder** [comment]
Thank you for the report & test case! I'll try to get this fixed ASAP; I assume your fix is valid, but just want to add test first etc. Will get nicely in 2.7.2.

**Comment by cowtowncoder** [comment]
Hmmh. Very interesting -- I have hard time reproducing this using anything other than binding into `JsonNode`. Still not quite sure why that makes a difference; it's not (as I first thought) due to use of `nextFieldName()` call, but something else. But at least it can be reproduced.

**Comment by cowtowncoder** [comment]
57 char limit makes sort of sense, although exposes a minor flaw in encoder (for ASCII-only name, should allow short form for up to 64 chars). But aside that, it's then different code path that causes the problem in 2.6/2.7.
