### ISSUE TITLE
Write JavaScript Library to Deserialize Smile

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-smile#9]
note: moved from http://jira.codehaus.org/browse/JACKSON-466 by Neil C -- also note that it was highly voted issue

-----

As powerful a binary format as Smile is proving to be on the server side, there are times when it is necessary to send binary format to the client. Rather than translate Smile to client-side binary format like AMF before transmission to the client, it would be much more seamless to use Smile on the client. A JavaScript library that understands Smile would lead to easier integration with the server and would help Smile gain greater traction as a binary JSON format--all the benefits of JSON we love with the efficiency of binary.

**Comment by cowtowncoder** [comment]
It does look like `smile-js` project: https://github.com/ngyewch/smile-js
might be just the thing! I have not tried, nor know what the limitations are (does it require node-js platform?), but code looks legit from what I can see.

**Comment by cowtowncoder** [comment]
Closing since an implementation exists, and since I have no plans to write one myself.

**Comment by Mart-Bogdan** [comment]
@cowtowncoder https://github.com/ngyewch/smile-js can nonly deserialize( no serializer so far

**Comment by cowtowncoder** [comment]
@Mart-Bogdan yes, that is what issue says. Could you please file another issue for serialization?

**Comment by Mart-Bogdan** [comment]
@cowtowncoder indeed, and this repo is deprecated.
Created Issue here: https://github.com/FasterXML/jackson-dataformats-binary/issues/131
